### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by workflowsguy** [fohrloop/wakepy#48]
Trying to open [wakepy.readthedocs.io](http://wakepy.readthedocs.io) gives 404 error

**Comment by fohrloop** [comment]
Thanks for the heads up! I'll take a look at it today or during the weekend.

**Comment by fohrloop** [comment]
The docs most probably broke when I (yesterday?) changed my GitHub username, which also changed the repo address. I updated the readthedocs settings. 

The docs should now be visible at: http://wakepy.readthedocs.io/
