### ISSUE TITLE
Invalid Keyword Argument for ActivationResult

### ISSUE THREAD

**Issue by EEsDoNotItNow** [fohrloop/wakepy#59]
With using they toy examples on my windows 10 machine, I get an invalid keyword argument for the ActivationResult seen here: https://github.com/fohrloop/wakepy/blob/5792c00cde782931e21f937a5f7846c434a8cdf8/wakepy/core/mode.py#L220

Checking the signature for this class, it is clear that __init__ does not accept this: https://github.com/fohrloop/wakepy/blob/5792c00cde782931e21f937a5f7846c434a8cdf8/wakepy/core/activationresult.py#L193

**Comment by fohrloop** [comment]
Hi @EEsDoNotItNow and thank you for the report! Could you confirm that which version or branch you're referring to?

**Comment by fohrloop** [comment]
I guess the tests were using the latest `dev` (master) branch at a time, which was unfortunately broken for some time. This should be fixed.
